name: Node.js CI/CD to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm test
      env: 
        NODE_ENV: test

    - name: Build
      run: npm run build

    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "your-heroku-app-name"
        heroku_email: "your-email@example.com"
